# 注意 yml 配置文件的编码格式 UTF-8
###########################################################################
server:
  # 端口
  port: 8001
  # 服务
  servlet:
    # 服务名
    context-path: /StudySpringBoot
###########################################################################
spring:
  ################################################################
  servlet:
    #上传文件配置
    multipart:
      #启用 http上传处理
      enabled: true
      #最大上传大小1G【默认1M】
      max-file-size: 1GB
  ################################################################
  # 数据源
  datasource:
    id: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库url
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    # 数据库用户名
    username: root
    # 数据库用户密码
    password: wyxjava123
  ################################################################
  # rabbitmq 消息队列配置文件
  rabbitmq:
    # 消息队列主机 ip 地址
    host: 127.0.0.1
    # 端口
    port: 5672
    # 用户名
    username: guest
    # 用户密码
    password: guest
    # 虚拟机
    virtualHost: /
  ################################################################
  # redis 配置项
  redis:
    # 主机地址
    host: 127.0.0.1
    #端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    #数据库索引
    database: 0
    #jedis
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 500
        #连接池中的最小空闲连接
        min-idle: 0
###########################################################################
# mybatis 框架
mybatis:
  # 别名包
  # xxxDo  xxx=数据库表名        Dao 层向外传输数据
  # xxxDto xxx=业务领域相关      Service 层向外传输数据
  # xxxVo  xxx=网页名称         Web 层向外传输
  type-aliases-package: com.gsm.model
  # mapper文件位置
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  # 配置
  configuration:
    # 数据库列名 user_name 映射pojo userName 格式转换
    map-underscore-to-camel-case: true
# log日志等级,mybatis打印sql
logging:
  level:
    com.gsm.dao: DEBUG
########################################################################
# 分页插件 pagehelper
pagehelper:
  # 数据库类型
  helper-dialect: mysql
  # 其他一些配置
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
  pageSizeZero: true

